pub mod audio;
pub mod crystal_manager;
pub mod curses;
#[cfg(not(target_os = "windows"))]
pub mod dbus;
pub mod general;
pub mod mouse;
pub mod preferences;
pub mod presence;
pub mod shuffle;
pub mod songs;
pub mod subtitle;
pub mod tui_ir;
pub mod utils;
